package com.uestc.fff.hotel.domain;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.City_ID
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.Country_Code
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.City_Name
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    private String cityName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.City_State
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    private String cityState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.City_ID
     *
     * @return the value of city.City_ID
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.City_ID
     *
     * @param cityId the value for city.City_ID
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.Country_Code
     *
     * @return the value of city.Country_Code
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.Country_Code
     *
     * @param countryCode the value for city.Country_Code
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.City_Name
     *
     * @return the value of city.City_Name
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.City_Name
     *
     * @param cityName the value for city.City_Name
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public void setCityName(String cityName) {
        this.cityName = cityName == null ? null : cityName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.City_State
     *
     * @return the value of city.City_State
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public String getCityState() {
        return cityState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.City_State
     *
     * @param cityState the value for city.City_State
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public void setCityState(String cityState) {
        this.cityState = cityState == null ? null : cityState.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        City other = (City) that;
        return (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getCityName() == null ? other.getCityName() == null : this.getCityName().equals(other.getCityName()))
            && (this.getCityState() == null ? other.getCityState() == null : this.getCityState().equals(other.getCityState()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getCityName() == null) ? 0 : getCityName().hashCode());
        result = prime * result + ((getCityState() == null) ? 0 : getCityState().hashCode());
        return result;
    }
}