package com.uestc.fff.hotel.domain;

import java.util.ArrayList;
import java.util.List;

public class ContinentExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public ContinentExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andContimentIdIsNull() {
            addCriterion("Contiment_ID is null");
            return (Criteria) this;
        }

        public Criteria andContimentIdIsNotNull() {
            addCriterion("Contiment_ID is not null");
            return (Criteria) this;
        }

        public Criteria andContimentIdEqualTo(String value) {
            addCriterion("Contiment_ID =", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdNotEqualTo(String value) {
            addCriterion("Contiment_ID <>", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdGreaterThan(String value) {
            addCriterion("Contiment_ID >", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdGreaterThanOrEqualTo(String value) {
            addCriterion("Contiment_ID >=", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdLessThan(String value) {
            addCriterion("Contiment_ID <", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdLessThanOrEqualTo(String value) {
            addCriterion("Contiment_ID <=", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdLike(String value) {
            addCriterion("Contiment_ID like", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdNotLike(String value) {
            addCriterion("Contiment_ID not like", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdIn(List<String> values) {
            addCriterion("Contiment_ID in", values, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdNotIn(List<String> values) {
            addCriterion("Contiment_ID not in", values, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdBetween(String value1, String value2) {
            addCriterion("Contiment_ID between", value1, value2, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdNotBetween(String value1, String value2) {
            addCriterion("Contiment_ID not between", value1, value2, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentNameIsNull() {
            addCriterion("Contiment_Name is null");
            return (Criteria) this;
        }

        public Criteria andContimentNameIsNotNull() {
            addCriterion("Contiment_Name is not null");
            return (Criteria) this;
        }

        public Criteria andContimentNameEqualTo(String value) {
            addCriterion("Contiment_Name =", value, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameNotEqualTo(String value) {
            addCriterion("Contiment_Name <>", value, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameGreaterThan(String value) {
            addCriterion("Contiment_Name >", value, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameGreaterThanOrEqualTo(String value) {
            addCriterion("Contiment_Name >=", value, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameLessThan(String value) {
            addCriterion("Contiment_Name <", value, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameLessThanOrEqualTo(String value) {
            addCriterion("Contiment_Name <=", value, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameLike(String value) {
            addCriterion("Contiment_Name like", value, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameNotLike(String value) {
            addCriterion("Contiment_Name not like", value, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameIn(List<String> values) {
            addCriterion("Contiment_Name in", values, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameNotIn(List<String> values) {
            addCriterion("Contiment_Name not in", values, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameBetween(String value1, String value2) {
            addCriterion("Contiment_Name between", value1, value2, "contimentName");
            return (Criteria) this;
        }

        public Criteria andContimentNameNotBetween(String value1, String value2) {
            addCriterion("Contiment_Name not between", value1, value2, "contimentName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table continent
     *
     * @mbg.generated do_not_delete_during_merge Thu Jul 25 14:23:43 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table continent
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}