package com.uestc.fff.hotel.domain;

public class Country {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Country_Code
     *
     * @mbg.generated Thu Jul 25 10:49:07 CST 2019
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column country.Country_Name
     *
     * @mbg.generated Thu Jul 25 10:49:07 CST 2019
     */
    private String countryName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Country_Code
     *
     * @return the value of country.Country_Code
     *
     * @mbg.generated Thu Jul 25 10:49:07 CST 2019
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Country_Code
     *
     * @param countryCode the value for country.Country_Code
     *
     * @mbg.generated Thu Jul 25 10:49:07 CST 2019
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column country.Country_Name
     *
     * @return the value of country.Country_Name
     *
     * @mbg.generated Thu Jul 25 10:49:07 CST 2019
     */
    public String getCountryName() {
        return countryName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column country.Country_Name
     *
     * @param countryName the value for country.Country_Name
     *
     * @mbg.generated Thu Jul 25 10:49:07 CST 2019
     */
    public void setCountryName(String countryName) {
        this.countryName = countryName == null ? null : countryName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Thu Jul 25 10:49:07 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Country other = (Country) that;
        return (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getCountryName() == null ? other.getCountryName() == null : this.getCountryName().equals(other.getCountryName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Thu Jul 25 10:49:07 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getCountryName() == null) ? 0 : getCountryName().hashCode());
        return result;
    }
}