package com.uestc.fff.hotel.domain;

import java.util.ArrayList;
import java.util.List;

public class HotelInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public HotelInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHotelIdIsNull() {
            addCriterion("Hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNotNull() {
            addCriterion("Hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andHotelIdEqualTo(String value) {
            addCriterion("Hotel_id =", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotEqualTo(String value) {
            addCriterion("Hotel_id <>", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThan(String value) {
            addCriterion("Hotel_id >", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_id >=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThan(String value) {
            addCriterion("Hotel_id <", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThanOrEqualTo(String value) {
            addCriterion("Hotel_id <=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLike(String value) {
            addCriterion("Hotel_id like", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotLike(String value) {
            addCriterion("Hotel_id not like", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdIn(List<String> values) {
            addCriterion("Hotel_id in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotIn(List<String> values) {
            addCriterion("Hotel_id not in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdBetween(String value1, String value2) {
            addCriterion("Hotel_id between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotBetween(String value1, String value2) {
            addCriterion("Hotel_id not between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andContimentIdIsNull() {
            addCriterion("Contiment_ID is null");
            return (Criteria) this;
        }

        public Criteria andContimentIdIsNotNull() {
            addCriterion("Contiment_ID is not null");
            return (Criteria) this;
        }

        public Criteria andContimentIdEqualTo(String value) {
            addCriterion("Contiment_ID =", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdNotEqualTo(String value) {
            addCriterion("Contiment_ID <>", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdGreaterThan(String value) {
            addCriterion("Contiment_ID >", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdGreaterThanOrEqualTo(String value) {
            addCriterion("Contiment_ID >=", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdLessThan(String value) {
            addCriterion("Contiment_ID <", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdLessThanOrEqualTo(String value) {
            addCriterion("Contiment_ID <=", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdLike(String value) {
            addCriterion("Contiment_ID like", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdNotLike(String value) {
            addCriterion("Contiment_ID not like", value, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdIn(List<String> values) {
            addCriterion("Contiment_ID in", values, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdNotIn(List<String> values) {
            addCriterion("Contiment_ID not in", values, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdBetween(String value1, String value2) {
            addCriterion("Contiment_ID between", value1, value2, "contimentId");
            return (Criteria) this;
        }

        public Criteria andContimentIdNotBetween(String value1, String value2) {
            addCriterion("Contiment_ID not between", value1, value2, "contimentId");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNull() {
            addCriterion("City_ID is null");
            return (Criteria) this;
        }

        public Criteria andCityIdIsNotNull() {
            addCriterion("City_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCityIdEqualTo(String value) {
            addCriterion("City_ID =", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotEqualTo(String value) {
            addCriterion("City_ID <>", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThan(String value) {
            addCriterion("City_ID >", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdGreaterThanOrEqualTo(String value) {
            addCriterion("City_ID >=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThan(String value) {
            addCriterion("City_ID <", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLessThanOrEqualTo(String value) {
            addCriterion("City_ID <=", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdLike(String value) {
            addCriterion("City_ID like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotLike(String value) {
            addCriterion("City_ID not like", value, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdIn(List<String> values) {
            addCriterion("City_ID in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotIn(List<String> values) {
            addCriterion("City_ID not in", values, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdBetween(String value1, String value2) {
            addCriterion("City_ID between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCityIdNotBetween(String value1, String value2) {
            addCriterion("City_ID not between", value1, value2, "cityId");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIsNull() {
            addCriterion("Country_Code is null");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIsNotNull() {
            addCriterion("Country_Code is not null");
            return (Criteria) this;
        }

        public Criteria andCountryCodeEqualTo(String value) {
            addCriterion("Country_Code =", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotEqualTo(String value) {
            addCriterion("Country_Code <>", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeGreaterThan(String value) {
            addCriterion("Country_Code >", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Country_Code >=", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLessThan(String value) {
            addCriterion("Country_Code <", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLessThanOrEqualTo(String value) {
            addCriterion("Country_Code <=", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeLike(String value) {
            addCriterion("Country_Code like", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotLike(String value) {
            addCriterion("Country_Code not like", value, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeIn(List<String> values) {
            addCriterion("Country_Code in", values, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotIn(List<String> values) {
            addCriterion("Country_Code not in", values, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeBetween(String value1, String value2) {
            addCriterion("Country_Code between", value1, value2, "countryCode");
            return (Criteria) this;
        }

        public Criteria andCountryCodeNotBetween(String value1, String value2) {
            addCriterion("Country_Code not between", value1, value2, "countryCode");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNull() {
            addCriterion("Hotel_name is null");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNotNull() {
            addCriterion("Hotel_name is not null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEqualTo(String value) {
            addCriterion("Hotel_name =", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotEqualTo(String value) {
            addCriterion("Hotel_name <>", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThan(String value) {
            addCriterion("Hotel_name >", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_name >=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThan(String value) {
            addCriterion("Hotel_name <", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThanOrEqualTo(String value) {
            addCriterion("Hotel_name <=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLike(String value) {
            addCriterion("Hotel_name like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotLike(String value) {
            addCriterion("Hotel_name not like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameIn(List<String> values) {
            addCriterion("Hotel_name in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotIn(List<String> values) {
            addCriterion("Hotel_name not in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameBetween(String value1, String value2) {
            addCriterion("Hotel_name between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotBetween(String value1, String value2) {
            addCriterion("Hotel_name not between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneIsNull() {
            addCriterion("Hotel_phone is null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneIsNotNull() {
            addCriterion("Hotel_phone is not null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneEqualTo(String value) {
            addCriterion("Hotel_phone =", value, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneNotEqualTo(String value) {
            addCriterion("Hotel_phone <>", value, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneGreaterThan(String value) {
            addCriterion("Hotel_phone >", value, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_phone >=", value, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneLessThan(String value) {
            addCriterion("Hotel_phone <", value, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneLessThanOrEqualTo(String value) {
            addCriterion("Hotel_phone <=", value, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneLike(String value) {
            addCriterion("Hotel_phone like", value, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneNotLike(String value) {
            addCriterion("Hotel_phone not like", value, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneIn(List<String> values) {
            addCriterion("Hotel_phone in", values, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneNotIn(List<String> values) {
            addCriterion("Hotel_phone not in", values, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneBetween(String value1, String value2) {
            addCriterion("Hotel_phone between", value1, value2, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelPhoneNotBetween(String value1, String value2) {
            addCriterion("Hotel_phone not between", value1, value2, "hotelPhone");
            return (Criteria) this;
        }

        public Criteria andHotelGradeIsNull() {
            addCriterion("Hotel_grade is null");
            return (Criteria) this;
        }

        public Criteria andHotelGradeIsNotNull() {
            addCriterion("Hotel_grade is not null");
            return (Criteria) this;
        }

        public Criteria andHotelGradeEqualTo(Integer value) {
            addCriterion("Hotel_grade =", value, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeNotEqualTo(Integer value) {
            addCriterion("Hotel_grade <>", value, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeGreaterThan(Integer value) {
            addCriterion("Hotel_grade >", value, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeGreaterThanOrEqualTo(Integer value) {
            addCriterion("Hotel_grade >=", value, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeLessThan(Integer value) {
            addCriterion("Hotel_grade <", value, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeLessThanOrEqualTo(Integer value) {
            addCriterion("Hotel_grade <=", value, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeIn(List<Integer> values) {
            addCriterion("Hotel_grade in", values, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeNotIn(List<Integer> values) {
            addCriterion("Hotel_grade not in", values, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeBetween(Integer value1, Integer value2) {
            addCriterion("Hotel_grade between", value1, value2, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelGradeNotBetween(Integer value1, Integer value2) {
            addCriterion("Hotel_grade not between", value1, value2, "hotelGrade");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIsNull() {
            addCriterion("Hotel_address is null");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIsNotNull() {
            addCriterion("Hotel_address is not null");
            return (Criteria) this;
        }

        public Criteria andHotelAddressEqualTo(String value) {
            addCriterion("Hotel_address =", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotEqualTo(String value) {
            addCriterion("Hotel_address <>", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressGreaterThan(String value) {
            addCriterion("Hotel_address >", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_address >=", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLessThan(String value) {
            addCriterion("Hotel_address <", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLessThanOrEqualTo(String value) {
            addCriterion("Hotel_address <=", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressLike(String value) {
            addCriterion("Hotel_address like", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotLike(String value) {
            addCriterion("Hotel_address not like", value, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressIn(List<String> values) {
            addCriterion("Hotel_address in", values, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotIn(List<String> values) {
            addCriterion("Hotel_address not in", values, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressBetween(String value1, String value2) {
            addCriterion("Hotel_address between", value1, value2, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelAddressNotBetween(String value1, String value2) {
            addCriterion("Hotel_address not between", value1, value2, "hotelAddress");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5IsNull() {
            addCriterion("Hotel_photo5 is null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5IsNotNull() {
            addCriterion("Hotel_photo5 is not null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5EqualTo(String value) {
            addCriterion("Hotel_photo5 =", value, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5NotEqualTo(String value) {
            addCriterion("Hotel_photo5 <>", value, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5GreaterThan(String value) {
            addCriterion("Hotel_photo5 >", value, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5GreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_photo5 >=", value, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5LessThan(String value) {
            addCriterion("Hotel_photo5 <", value, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5LessThanOrEqualTo(String value) {
            addCriterion("Hotel_photo5 <=", value, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5Like(String value) {
            addCriterion("Hotel_photo5 like", value, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5NotLike(String value) {
            addCriterion("Hotel_photo5 not like", value, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5In(List<String> values) {
            addCriterion("Hotel_photo5 in", values, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5NotIn(List<String> values) {
            addCriterion("Hotel_photo5 not in", values, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5Between(String value1, String value2) {
            addCriterion("Hotel_photo5 between", value1, value2, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto5NotBetween(String value1, String value2) {
            addCriterion("Hotel_photo5 not between", value1, value2, "hotelPhoto5");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4IsNull() {
            addCriterion("Hotel_photo4 is null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4IsNotNull() {
            addCriterion("Hotel_photo4 is not null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4EqualTo(String value) {
            addCriterion("Hotel_photo4 =", value, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4NotEqualTo(String value) {
            addCriterion("Hotel_photo4 <>", value, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4GreaterThan(String value) {
            addCriterion("Hotel_photo4 >", value, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4GreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_photo4 >=", value, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4LessThan(String value) {
            addCriterion("Hotel_photo4 <", value, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4LessThanOrEqualTo(String value) {
            addCriterion("Hotel_photo4 <=", value, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4Like(String value) {
            addCriterion("Hotel_photo4 like", value, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4NotLike(String value) {
            addCriterion("Hotel_photo4 not like", value, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4In(List<String> values) {
            addCriterion("Hotel_photo4 in", values, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4NotIn(List<String> values) {
            addCriterion("Hotel_photo4 not in", values, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4Between(String value1, String value2) {
            addCriterion("Hotel_photo4 between", value1, value2, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto4NotBetween(String value1, String value2) {
            addCriterion("Hotel_photo4 not between", value1, value2, "hotelPhoto4");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3IsNull() {
            addCriterion("Hotel_photo3 is null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3IsNotNull() {
            addCriterion("Hotel_photo3 is not null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3EqualTo(String value) {
            addCriterion("Hotel_photo3 =", value, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3NotEqualTo(String value) {
            addCriterion("Hotel_photo3 <>", value, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3GreaterThan(String value) {
            addCriterion("Hotel_photo3 >", value, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3GreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_photo3 >=", value, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3LessThan(String value) {
            addCriterion("Hotel_photo3 <", value, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3LessThanOrEqualTo(String value) {
            addCriterion("Hotel_photo3 <=", value, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3Like(String value) {
            addCriterion("Hotel_photo3 like", value, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3NotLike(String value) {
            addCriterion("Hotel_photo3 not like", value, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3In(List<String> values) {
            addCriterion("Hotel_photo3 in", values, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3NotIn(List<String> values) {
            addCriterion("Hotel_photo3 not in", values, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3Between(String value1, String value2) {
            addCriterion("Hotel_photo3 between", value1, value2, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto3NotBetween(String value1, String value2) {
            addCriterion("Hotel_photo3 not between", value1, value2, "hotelPhoto3");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2IsNull() {
            addCriterion("Hotel_photo2 is null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2IsNotNull() {
            addCriterion("Hotel_photo2 is not null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2EqualTo(String value) {
            addCriterion("Hotel_photo2 =", value, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2NotEqualTo(String value) {
            addCriterion("Hotel_photo2 <>", value, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2GreaterThan(String value) {
            addCriterion("Hotel_photo2 >", value, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2GreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_photo2 >=", value, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2LessThan(String value) {
            addCriterion("Hotel_photo2 <", value, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2LessThanOrEqualTo(String value) {
            addCriterion("Hotel_photo2 <=", value, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2Like(String value) {
            addCriterion("Hotel_photo2 like", value, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2NotLike(String value) {
            addCriterion("Hotel_photo2 not like", value, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2In(List<String> values) {
            addCriterion("Hotel_photo2 in", values, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2NotIn(List<String> values) {
            addCriterion("Hotel_photo2 not in", values, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2Between(String value1, String value2) {
            addCriterion("Hotel_photo2 between", value1, value2, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto2NotBetween(String value1, String value2) {
            addCriterion("Hotel_photo2 not between", value1, value2, "hotelPhoto2");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1IsNull() {
            addCriterion("Hotel_photo1 is null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1IsNotNull() {
            addCriterion("Hotel_photo1 is not null");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1EqualTo(String value) {
            addCriterion("Hotel_photo1 =", value, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1NotEqualTo(String value) {
            addCriterion("Hotel_photo1 <>", value, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1GreaterThan(String value) {
            addCriterion("Hotel_photo1 >", value, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1GreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_photo1 >=", value, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1LessThan(String value) {
            addCriterion("Hotel_photo1 <", value, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1LessThanOrEqualTo(String value) {
            addCriterion("Hotel_photo1 <=", value, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1Like(String value) {
            addCriterion("Hotel_photo1 like", value, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1NotLike(String value) {
            addCriterion("Hotel_photo1 not like", value, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1In(List<String> values) {
            addCriterion("Hotel_photo1 in", values, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1NotIn(List<String> values) {
            addCriterion("Hotel_photo1 not in", values, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1Between(String value1, String value2) {
            addCriterion("Hotel_photo1 between", value1, value2, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelPhoto1NotBetween(String value1, String value2) {
            addCriterion("Hotel_photo1 not between", value1, value2, "hotelPhoto1");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnIsNull() {
            addCriterion("Hotel_name_en is null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnIsNotNull() {
            addCriterion("Hotel_name_en is not null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnEqualTo(String value) {
            addCriterion("Hotel_name_en =", value, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnNotEqualTo(String value) {
            addCriterion("Hotel_name_en <>", value, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnGreaterThan(String value) {
            addCriterion("Hotel_name_en >", value, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_name_en >=", value, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnLessThan(String value) {
            addCriterion("Hotel_name_en <", value, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnLessThanOrEqualTo(String value) {
            addCriterion("Hotel_name_en <=", value, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnLike(String value) {
            addCriterion("Hotel_name_en like", value, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnNotLike(String value) {
            addCriterion("Hotel_name_en not like", value, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnIn(List<String> values) {
            addCriterion("Hotel_name_en in", values, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnNotIn(List<String> values) {
            addCriterion("Hotel_name_en not in", values, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnBetween(String value1, String value2) {
            addCriterion("Hotel_name_en between", value1, value2, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelNameEnNotBetween(String value1, String value2) {
            addCriterion("Hotel_name_en not between", value1, value2, "hotelNameEn");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeIsNull() {
            addCriterion("Hotel_zipcode is null");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeIsNotNull() {
            addCriterion("Hotel_zipcode is not null");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeEqualTo(String value) {
            addCriterion("Hotel_zipcode =", value, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeNotEqualTo(String value) {
            addCriterion("Hotel_zipcode <>", value, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeGreaterThan(String value) {
            addCriterion("Hotel_zipcode >", value, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_zipcode >=", value, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeLessThan(String value) {
            addCriterion("Hotel_zipcode <", value, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeLessThanOrEqualTo(String value) {
            addCriterion("Hotel_zipcode <=", value, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeLike(String value) {
            addCriterion("Hotel_zipcode like", value, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeNotLike(String value) {
            addCriterion("Hotel_zipcode not like", value, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeIn(List<String> values) {
            addCriterion("Hotel_zipcode in", values, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeNotIn(List<String> values) {
            addCriterion("Hotel_zipcode not in", values, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeBetween(String value1, String value2) {
            addCriterion("Hotel_zipcode between", value1, value2, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelZipcodeNotBetween(String value1, String value2) {
            addCriterion("Hotel_zipcode not between", value1, value2, "hotelZipcode");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinIsNull() {
            addCriterion("Hotel_checkin is null");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinIsNotNull() {
            addCriterion("Hotel_checkin is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinEqualTo(String value) {
            addCriterion("Hotel_checkin =", value, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinNotEqualTo(String value) {
            addCriterion("Hotel_checkin <>", value, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinGreaterThan(String value) {
            addCriterion("Hotel_checkin >", value, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_checkin >=", value, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinLessThan(String value) {
            addCriterion("Hotel_checkin <", value, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinLessThanOrEqualTo(String value) {
            addCriterion("Hotel_checkin <=", value, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinLike(String value) {
            addCriterion("Hotel_checkin like", value, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinNotLike(String value) {
            addCriterion("Hotel_checkin not like", value, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinIn(List<String> values) {
            addCriterion("Hotel_checkin in", values, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinNotIn(List<String> values) {
            addCriterion("Hotel_checkin not in", values, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinBetween(String value1, String value2) {
            addCriterion("Hotel_checkin between", value1, value2, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckinNotBetween(String value1, String value2) {
            addCriterion("Hotel_checkin not between", value1, value2, "hotelCheckin");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutIsNull() {
            addCriterion("Hotel_checkout is null");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutIsNotNull() {
            addCriterion("Hotel_checkout is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutEqualTo(String value) {
            addCriterion("Hotel_checkout =", value, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutNotEqualTo(String value) {
            addCriterion("Hotel_checkout <>", value, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutGreaterThan(String value) {
            addCriterion("Hotel_checkout >", value, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_checkout >=", value, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutLessThan(String value) {
            addCriterion("Hotel_checkout <", value, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutLessThanOrEqualTo(String value) {
            addCriterion("Hotel_checkout <=", value, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutLike(String value) {
            addCriterion("Hotel_checkout like", value, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutNotLike(String value) {
            addCriterion("Hotel_checkout not like", value, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutIn(List<String> values) {
            addCriterion("Hotel_checkout in", values, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutNotIn(List<String> values) {
            addCriterion("Hotel_checkout not in", values, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutBetween(String value1, String value2) {
            addCriterion("Hotel_checkout between", value1, value2, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelCheckoutNotBetween(String value1, String value2) {
            addCriterion("Hotel_checkout not between", value1, value2, "hotelCheckout");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumIsNull() {
            addCriterion("Hotel_roomnum is null");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumIsNotNull() {
            addCriterion("Hotel_roomnum is not null");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumEqualTo(Integer value) {
            addCriterion("Hotel_roomnum =", value, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumNotEqualTo(Integer value) {
            addCriterion("Hotel_roomnum <>", value, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumGreaterThan(Integer value) {
            addCriterion("Hotel_roomnum >", value, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("Hotel_roomnum >=", value, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumLessThan(Integer value) {
            addCriterion("Hotel_roomnum <", value, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumLessThanOrEqualTo(Integer value) {
            addCriterion("Hotel_roomnum <=", value, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumIn(List<Integer> values) {
            addCriterion("Hotel_roomnum in", values, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumNotIn(List<Integer> values) {
            addCriterion("Hotel_roomnum not in", values, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumBetween(Integer value1, Integer value2) {
            addCriterion("Hotel_roomnum between", value1, value2, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRoomnumNotBetween(Integer value1, Integer value2) {
            addCriterion("Hotel_roomnum not between", value1, value2, "hotelRoomnum");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromIsNull() {
            addCriterion("Hotel_ratesfrom is null");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromIsNotNull() {
            addCriterion("Hotel_ratesfrom is not null");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromEqualTo(Float value) {
            addCriterion("Hotel_ratesfrom =", value, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromNotEqualTo(Float value) {
            addCriterion("Hotel_ratesfrom <>", value, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromGreaterThan(Float value) {
            addCriterion("Hotel_ratesfrom >", value, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromGreaterThanOrEqualTo(Float value) {
            addCriterion("Hotel_ratesfrom >=", value, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromLessThan(Float value) {
            addCriterion("Hotel_ratesfrom <", value, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromLessThanOrEqualTo(Float value) {
            addCriterion("Hotel_ratesfrom <=", value, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromIn(List<Float> values) {
            addCriterion("Hotel_ratesfrom in", values, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromNotIn(List<Float> values) {
            addCriterion("Hotel_ratesfrom not in", values, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromBetween(Float value1, Float value2) {
            addCriterion("Hotel_ratesfrom between", value1, value2, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatesfromNotBetween(Float value1, Float value2) {
            addCriterion("Hotel_ratesfrom not between", value1, value2, "hotelRatesfrom");
            return (Criteria) this;
        }

        public Criteria andHotelRatingIsNull() {
            addCriterion("Hotel_rating is null");
            return (Criteria) this;
        }

        public Criteria andHotelRatingIsNotNull() {
            addCriterion("Hotel_rating is not null");
            return (Criteria) this;
        }

        public Criteria andHotelRatingEqualTo(Float value) {
            addCriterion("Hotel_rating =", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingNotEqualTo(Float value) {
            addCriterion("Hotel_rating <>", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingGreaterThan(Float value) {
            addCriterion("Hotel_rating >", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingGreaterThanOrEqualTo(Float value) {
            addCriterion("Hotel_rating >=", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingLessThan(Float value) {
            addCriterion("Hotel_rating <", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingLessThanOrEqualTo(Float value) {
            addCriterion("Hotel_rating <=", value, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingIn(List<Float> values) {
            addCriterion("Hotel_rating in", values, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingNotIn(List<Float> values) {
            addCriterion("Hotel_rating not in", values, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingBetween(Float value1, Float value2) {
            addCriterion("Hotel_rating between", value1, value2, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelRatingNotBetween(Float value1, Float value2) {
            addCriterion("Hotel_rating not between", value1, value2, "hotelRating");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyIsNull() {
            addCriterion("Hotel_currency is null");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyIsNotNull() {
            addCriterion("Hotel_currency is not null");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyEqualTo(String value) {
            addCriterion("Hotel_currency =", value, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyNotEqualTo(String value) {
            addCriterion("Hotel_currency <>", value, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyGreaterThan(String value) {
            addCriterion("Hotel_currency >", value, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyGreaterThanOrEqualTo(String value) {
            addCriterion("Hotel_currency >=", value, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyLessThan(String value) {
            addCriterion("Hotel_currency <", value, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyLessThanOrEqualTo(String value) {
            addCriterion("Hotel_currency <=", value, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyLike(String value) {
            addCriterion("Hotel_currency like", value, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyNotLike(String value) {
            addCriterion("Hotel_currency not like", value, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyIn(List<String> values) {
            addCriterion("Hotel_currency in", values, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyNotIn(List<String> values) {
            addCriterion("Hotel_currency not in", values, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyBetween(String value1, String value2) {
            addCriterion("Hotel_currency between", value1, value2, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelCurrencyNotBetween(String value1, String value2) {
            addCriterion("Hotel_currency not between", value1, value2, "hotelCurrency");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumIsNull() {
            addCriterion("Hotel_reviewnum is null");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumIsNotNull() {
            addCriterion("Hotel_reviewnum is not null");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumEqualTo(Integer value) {
            addCriterion("Hotel_reviewnum =", value, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumNotEqualTo(Integer value) {
            addCriterion("Hotel_reviewnum <>", value, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumGreaterThan(Integer value) {
            addCriterion("Hotel_reviewnum >", value, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumGreaterThanOrEqualTo(Integer value) {
            addCriterion("Hotel_reviewnum >=", value, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumLessThan(Integer value) {
            addCriterion("Hotel_reviewnum <", value, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumLessThanOrEqualTo(Integer value) {
            addCriterion("Hotel_reviewnum <=", value, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumIn(List<Integer> values) {
            addCriterion("Hotel_reviewnum in", values, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumNotIn(List<Integer> values) {
            addCriterion("Hotel_reviewnum not in", values, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumBetween(Integer value1, Integer value2) {
            addCriterion("Hotel_reviewnum between", value1, value2, "hotelReviewnum");
            return (Criteria) this;
        }

        public Criteria andHotelReviewnumNotBetween(Integer value1, Integer value2) {
            addCriterion("Hotel_reviewnum not between", value1, value2, "hotelReviewnum");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 30 15:53:19 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hotel_info
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}