package com.uestc.fff.hotel.domain;

public class HotelInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_id
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Contiment_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String contimentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.City_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String cityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Country_Code
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String countryCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_name
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_phone
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_grade
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private Integer hotelGrade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_address
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_photo5
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelPhoto5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_photo4
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelPhoto4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_photo3
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelPhoto3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_photo2
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelPhoto2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_photo1
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelPhoto1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_name_en
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelNameEn;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_zipcode
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelZipcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_checkin
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelCheckin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_checkout
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelCheckout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_roomnum
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private Integer hotelRoomnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_ratesfrom
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private Float hotelRatesfrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_rating
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private Float hotelRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_currency
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelCurrency;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_reviewnum
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private Integer hotelReviewnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_longitude
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private Double hotelLongitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_latitude
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private Double hotelLatitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hotel_info.Hotel_overview
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String hotelOverview;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_id
     *
     * @return the value of hotel_info.Hotel_id
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_id
     *
     * @param hotelId the value for hotel_info.Hotel_id
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelId(String hotelId) {
        this.hotelId = hotelId == null ? null : hotelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Contiment_ID
     *
     * @return the value of hotel_info.Contiment_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getContimentId() {
        return contimentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Contiment_ID
     *
     * @param contimentId the value for hotel_info.Contiment_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setContimentId(String contimentId) {
        this.contimentId = contimentId == null ? null : contimentId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.City_ID
     *
     * @return the value of hotel_info.City_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.City_ID
     *
     * @param cityId the value for hotel_info.City_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setCityId(String cityId) {
        this.cityId = cityId == null ? null : cityId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Country_Code
     *
     * @return the value of hotel_info.Country_Code
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Country_Code
     *
     * @param countryCode the value for hotel_info.Country_Code
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_name
     *
     * @return the value of hotel_info.Hotel_name
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_name
     *
     * @param hotelName the value for hotel_info.Hotel_name
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_phone
     *
     * @return the value of hotel_info.Hotel_phone
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelPhone() {
        return hotelPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_phone
     *
     * @param hotelPhone the value for hotel_info.Hotel_phone
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelPhone(String hotelPhone) {
        this.hotelPhone = hotelPhone == null ? null : hotelPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_grade
     *
     * @return the value of hotel_info.Hotel_grade
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public Integer getHotelGrade() {
        return hotelGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_grade
     *
     * @param hotelGrade the value for hotel_info.Hotel_grade
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelGrade(Integer hotelGrade) {
        this.hotelGrade = hotelGrade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_address
     *
     * @return the value of hotel_info.Hotel_address
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelAddress() {
        return hotelAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_address
     *
     * @param hotelAddress the value for hotel_info.Hotel_address
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelAddress(String hotelAddress) {
        this.hotelAddress = hotelAddress == null ? null : hotelAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_photo5
     *
     * @return the value of hotel_info.Hotel_photo5
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelPhoto5() {
        return hotelPhoto5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_photo5
     *
     * @param hotelPhoto5 the value for hotel_info.Hotel_photo5
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelPhoto5(String hotelPhoto5) {
        this.hotelPhoto5 = hotelPhoto5 == null ? null : hotelPhoto5.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_photo4
     *
     * @return the value of hotel_info.Hotel_photo4
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelPhoto4() {
        return hotelPhoto4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_photo4
     *
     * @param hotelPhoto4 the value for hotel_info.Hotel_photo4
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelPhoto4(String hotelPhoto4) {
        this.hotelPhoto4 = hotelPhoto4 == null ? null : hotelPhoto4.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_photo3
     *
     * @return the value of hotel_info.Hotel_photo3
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelPhoto3() {
        return hotelPhoto3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_photo3
     *
     * @param hotelPhoto3 the value for hotel_info.Hotel_photo3
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelPhoto3(String hotelPhoto3) {
        this.hotelPhoto3 = hotelPhoto3 == null ? null : hotelPhoto3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_photo2
     *
     * @return the value of hotel_info.Hotel_photo2
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelPhoto2() {
        return hotelPhoto2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_photo2
     *
     * @param hotelPhoto2 the value for hotel_info.Hotel_photo2
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelPhoto2(String hotelPhoto2) {
        this.hotelPhoto2 = hotelPhoto2 == null ? null : hotelPhoto2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_photo1
     *
     * @return the value of hotel_info.Hotel_photo1
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelPhoto1() {
        return hotelPhoto1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_photo1
     *
     * @param hotelPhoto1 the value for hotel_info.Hotel_photo1
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelPhoto1(String hotelPhoto1) {
        this.hotelPhoto1 = hotelPhoto1 == null ? null : hotelPhoto1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_name_en
     *
     * @return the value of hotel_info.Hotel_name_en
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelNameEn() {
        return hotelNameEn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_name_en
     *
     * @param hotelNameEn the value for hotel_info.Hotel_name_en
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelNameEn(String hotelNameEn) {
        this.hotelNameEn = hotelNameEn == null ? null : hotelNameEn.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_zipcode
     *
     * @return the value of hotel_info.Hotel_zipcode
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelZipcode() {
        return hotelZipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_zipcode
     *
     * @param hotelZipcode the value for hotel_info.Hotel_zipcode
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelZipcode(String hotelZipcode) {
        this.hotelZipcode = hotelZipcode == null ? null : hotelZipcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_checkin
     *
     * @return the value of hotel_info.Hotel_checkin
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelCheckin() {
        return hotelCheckin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_checkin
     *
     * @param hotelCheckin the value for hotel_info.Hotel_checkin
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelCheckin(String hotelCheckin) {
        this.hotelCheckin = hotelCheckin == null ? null : hotelCheckin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_checkout
     *
     * @return the value of hotel_info.Hotel_checkout
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelCheckout() {
        return hotelCheckout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_checkout
     *
     * @param hotelCheckout the value for hotel_info.Hotel_checkout
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelCheckout(String hotelCheckout) {
        this.hotelCheckout = hotelCheckout == null ? null : hotelCheckout.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_roomnum
     *
     * @return the value of hotel_info.Hotel_roomnum
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public Integer getHotelRoomnum() {
        return hotelRoomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_roomnum
     *
     * @param hotelRoomnum the value for hotel_info.Hotel_roomnum
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelRoomnum(Integer hotelRoomnum) {
        this.hotelRoomnum = hotelRoomnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_ratesfrom
     *
     * @return the value of hotel_info.Hotel_ratesfrom
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public Float getHotelRatesfrom() {
        return hotelRatesfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_ratesfrom
     *
     * @param hotelRatesfrom the value for hotel_info.Hotel_ratesfrom
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelRatesfrom(Float hotelRatesfrom) {
        this.hotelRatesfrom = hotelRatesfrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_rating
     *
     * @return the value of hotel_info.Hotel_rating
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public Float getHotelRating() {
        return hotelRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_rating
     *
     * @param hotelRating the value for hotel_info.Hotel_rating
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelRating(Float hotelRating) {
        this.hotelRating = hotelRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_currency
     *
     * @return the value of hotel_info.Hotel_currency
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelCurrency() {
        return hotelCurrency;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_currency
     *
     * @param hotelCurrency the value for hotel_info.Hotel_currency
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelCurrency(String hotelCurrency) {
        this.hotelCurrency = hotelCurrency == null ? null : hotelCurrency.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_reviewnum
     *
     * @return the value of hotel_info.Hotel_reviewnum
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public Integer getHotelReviewnum() {
        return hotelReviewnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_reviewnum
     *
     * @param hotelReviewnum the value for hotel_info.Hotel_reviewnum
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelReviewnum(Integer hotelReviewnum) {
        this.hotelReviewnum = hotelReviewnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_longitude
     *
     * @return the value of hotel_info.Hotel_longitude
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public Double getHotelLongitude() {
        return hotelLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_longitude
     *
     * @param hotelLongitude the value for hotel_info.Hotel_longitude
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelLongitude(Double hotelLongitude) {
        this.hotelLongitude = hotelLongitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_latitude
     *
     * @return the value of hotel_info.Hotel_latitude
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public Double getHotelLatitude() {
        return hotelLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_latitude
     *
     * @param hotelLatitude the value for hotel_info.Hotel_latitude
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelLatitude(Double hotelLatitude) {
        this.hotelLatitude = hotelLatitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hotel_info.Hotel_overview
     *
     * @return the value of hotel_info.Hotel_overview
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getHotelOverview() {
        return hotelOverview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hotel_info.Hotel_overview
     *
     * @param hotelOverview the value for hotel_info.Hotel_overview
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setHotelOverview(String hotelOverview) {
        this.hotelOverview = hotelOverview == null ? null : hotelOverview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HotelInfo other = (HotelInfo) that;
        return (this.getHotelId() == null ? other.getHotelId() == null : this.getHotelId().equals(other.getHotelId()))
            && (this.getContimentId() == null ? other.getContimentId() == null : this.getContimentId().equals(other.getContimentId()))
            && (this.getCityId() == null ? other.getCityId() == null : this.getCityId().equals(other.getCityId()))
            && (this.getCountryCode() == null ? other.getCountryCode() == null : this.getCountryCode().equals(other.getCountryCode()))
            && (this.getHotelName() == null ? other.getHotelName() == null : this.getHotelName().equals(other.getHotelName()))
            && (this.getHotelPhone() == null ? other.getHotelPhone() == null : this.getHotelPhone().equals(other.getHotelPhone()))
            && (this.getHotelGrade() == null ? other.getHotelGrade() == null : this.getHotelGrade().equals(other.getHotelGrade()))
            && (this.getHotelAddress() == null ? other.getHotelAddress() == null : this.getHotelAddress().equals(other.getHotelAddress()))
            && (this.getHotelPhoto5() == null ? other.getHotelPhoto5() == null : this.getHotelPhoto5().equals(other.getHotelPhoto5()))
            && (this.getHotelPhoto4() == null ? other.getHotelPhoto4() == null : this.getHotelPhoto4().equals(other.getHotelPhoto4()))
            && (this.getHotelPhoto3() == null ? other.getHotelPhoto3() == null : this.getHotelPhoto3().equals(other.getHotelPhoto3()))
            && (this.getHotelPhoto2() == null ? other.getHotelPhoto2() == null : this.getHotelPhoto2().equals(other.getHotelPhoto2()))
            && (this.getHotelPhoto1() == null ? other.getHotelPhoto1() == null : this.getHotelPhoto1().equals(other.getHotelPhoto1()))
            && (this.getHotelNameEn() == null ? other.getHotelNameEn() == null : this.getHotelNameEn().equals(other.getHotelNameEn()))
            && (this.getHotelZipcode() == null ? other.getHotelZipcode() == null : this.getHotelZipcode().equals(other.getHotelZipcode()))
            && (this.getHotelCheckin() == null ? other.getHotelCheckin() == null : this.getHotelCheckin().equals(other.getHotelCheckin()))
            && (this.getHotelCheckout() == null ? other.getHotelCheckout() == null : this.getHotelCheckout().equals(other.getHotelCheckout()))
            && (this.getHotelRoomnum() == null ? other.getHotelRoomnum() == null : this.getHotelRoomnum().equals(other.getHotelRoomnum()))
            && (this.getHotelRatesfrom() == null ? other.getHotelRatesfrom() == null : this.getHotelRatesfrom().equals(other.getHotelRatesfrom()))
            && (this.getHotelRating() == null ? other.getHotelRating() == null : this.getHotelRating().equals(other.getHotelRating()))
            && (this.getHotelCurrency() == null ? other.getHotelCurrency() == null : this.getHotelCurrency().equals(other.getHotelCurrency()))
            && (this.getHotelReviewnum() == null ? other.getHotelReviewnum() == null : this.getHotelReviewnum().equals(other.getHotelReviewnum()))
            && (this.getHotelLongitude() == null ? other.getHotelLongitude() == null : this.getHotelLongitude().equals(other.getHotelLongitude()))
            && (this.getHotelLatitude() == null ? other.getHotelLatitude() == null : this.getHotelLatitude().equals(other.getHotelLatitude()))
            && (this.getHotelOverview() == null ? other.getHotelOverview() == null : this.getHotelOverview().equals(other.getHotelOverview()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHotelId() == null) ? 0 : getHotelId().hashCode());
        result = prime * result + ((getContimentId() == null) ? 0 : getContimentId().hashCode());
        result = prime * result + ((getCityId() == null) ? 0 : getCityId().hashCode());
        result = prime * result + ((getCountryCode() == null) ? 0 : getCountryCode().hashCode());
        result = prime * result + ((getHotelName() == null) ? 0 : getHotelName().hashCode());
        result = prime * result + ((getHotelPhone() == null) ? 0 : getHotelPhone().hashCode());
        result = prime * result + ((getHotelGrade() == null) ? 0 : getHotelGrade().hashCode());
        result = prime * result + ((getHotelAddress() == null) ? 0 : getHotelAddress().hashCode());
        result = prime * result + ((getHotelPhoto5() == null) ? 0 : getHotelPhoto5().hashCode());
        result = prime * result + ((getHotelPhoto4() == null) ? 0 : getHotelPhoto4().hashCode());
        result = prime * result + ((getHotelPhoto3() == null) ? 0 : getHotelPhoto3().hashCode());
        result = prime * result + ((getHotelPhoto2() == null) ? 0 : getHotelPhoto2().hashCode());
        result = prime * result + ((getHotelPhoto1() == null) ? 0 : getHotelPhoto1().hashCode());
        result = prime * result + ((getHotelNameEn() == null) ? 0 : getHotelNameEn().hashCode());
        result = prime * result + ((getHotelZipcode() == null) ? 0 : getHotelZipcode().hashCode());
        result = prime * result + ((getHotelCheckin() == null) ? 0 : getHotelCheckin().hashCode());
        result = prime * result + ((getHotelCheckout() == null) ? 0 : getHotelCheckout().hashCode());
        result = prime * result + ((getHotelRoomnum() == null) ? 0 : getHotelRoomnum().hashCode());
        result = prime * result + ((getHotelRatesfrom() == null) ? 0 : getHotelRatesfrom().hashCode());
        result = prime * result + ((getHotelRating() == null) ? 0 : getHotelRating().hashCode());
        result = prime * result + ((getHotelCurrency() == null) ? 0 : getHotelCurrency().hashCode());
        result = prime * result + ((getHotelReviewnum() == null) ? 0 : getHotelReviewnum().hashCode());
        result = prime * result + ((getHotelLongitude() == null) ? 0 : getHotelLongitude().hashCode());
        result = prime * result + ((getHotelLatitude() == null) ? 0 : getHotelLatitude().hashCode());
        result = prime * result + ((getHotelOverview() == null) ? 0 : getHotelOverview().hashCode());
        return result;
    }
}