package com.uestc.fff.hotel.domain;

import java.util.ArrayList;
import java.util.List;

public class OrderTRExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public OrderTRExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(String value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(String value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(String value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(String value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(String value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(String value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLike(String value) {
            addCriterion("id like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotLike(String value) {
            addCriterion("id not like", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<String> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<String> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(String value1, String value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(String value1, String value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNull() {
            addCriterion("Order_ID is null");
            return (Criteria) this;
        }

        public Criteria andOrderIdIsNotNull() {
            addCriterion("Order_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOrderIdEqualTo(String value) {
            addCriterion("Order_ID =", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotEqualTo(String value) {
            addCriterion("Order_ID <>", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThan(String value) {
            addCriterion("Order_ID >", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdGreaterThanOrEqualTo(String value) {
            addCriterion("Order_ID >=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThan(String value) {
            addCriterion("Order_ID <", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLessThanOrEqualTo(String value) {
            addCriterion("Order_ID <=", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdLike(String value) {
            addCriterion("Order_ID like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotLike(String value) {
            addCriterion("Order_ID not like", value, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdIn(List<String> values) {
            addCriterion("Order_ID in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotIn(List<String> values) {
            addCriterion("Order_ID not in", values, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdBetween(String value1, String value2) {
            addCriterion("Order_ID between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andOrderIdNotBetween(String value1, String value2) {
            addCriterion("Order_ID not between", value1, value2, "orderId");
            return (Criteria) this;
        }

        public Criteria andRoomId1IsNull() {
            addCriterion("Room_ID1 is null");
            return (Criteria) this;
        }

        public Criteria andRoomId1IsNotNull() {
            addCriterion("Room_ID1 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomId1EqualTo(String value) {
            addCriterion("Room_ID1 =", value, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1NotEqualTo(String value) {
            addCriterion("Room_ID1 <>", value, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1GreaterThan(String value) {
            addCriterion("Room_ID1 >", value, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1GreaterThanOrEqualTo(String value) {
            addCriterion("Room_ID1 >=", value, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1LessThan(String value) {
            addCriterion("Room_ID1 <", value, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1LessThanOrEqualTo(String value) {
            addCriterion("Room_ID1 <=", value, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1Like(String value) {
            addCriterion("Room_ID1 like", value, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1NotLike(String value) {
            addCriterion("Room_ID1 not like", value, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1In(List<String> values) {
            addCriterion("Room_ID1 in", values, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1NotIn(List<String> values) {
            addCriterion("Room_ID1 not in", values, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1Between(String value1, String value2) {
            addCriterion("Room_ID1 between", value1, value2, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId1NotBetween(String value1, String value2) {
            addCriterion("Room_ID1 not between", value1, value2, "roomId1");
            return (Criteria) this;
        }

        public Criteria andRoomId2IsNull() {
            addCriterion("Room_ID2 is null");
            return (Criteria) this;
        }

        public Criteria andRoomId2IsNotNull() {
            addCriterion("Room_ID2 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomId2EqualTo(String value) {
            addCriterion("Room_ID2 =", value, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2NotEqualTo(String value) {
            addCriterion("Room_ID2 <>", value, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2GreaterThan(String value) {
            addCriterion("Room_ID2 >", value, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2GreaterThanOrEqualTo(String value) {
            addCriterion("Room_ID2 >=", value, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2LessThan(String value) {
            addCriterion("Room_ID2 <", value, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2LessThanOrEqualTo(String value) {
            addCriterion("Room_ID2 <=", value, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2Like(String value) {
            addCriterion("Room_ID2 like", value, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2NotLike(String value) {
            addCriterion("Room_ID2 not like", value, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2In(List<String> values) {
            addCriterion("Room_ID2 in", values, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2NotIn(List<String> values) {
            addCriterion("Room_ID2 not in", values, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2Between(String value1, String value2) {
            addCriterion("Room_ID2 between", value1, value2, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId2NotBetween(String value1, String value2) {
            addCriterion("Room_ID2 not between", value1, value2, "roomId2");
            return (Criteria) this;
        }

        public Criteria andRoomId3IsNull() {
            addCriterion("Room_ID3 is null");
            return (Criteria) this;
        }

        public Criteria andRoomId3IsNotNull() {
            addCriterion("Room_ID3 is not null");
            return (Criteria) this;
        }

        public Criteria andRoomId3EqualTo(String value) {
            addCriterion("Room_ID3 =", value, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3NotEqualTo(String value) {
            addCriterion("Room_ID3 <>", value, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3GreaterThan(String value) {
            addCriterion("Room_ID3 >", value, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3GreaterThanOrEqualTo(String value) {
            addCriterion("Room_ID3 >=", value, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3LessThan(String value) {
            addCriterion("Room_ID3 <", value, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3LessThanOrEqualTo(String value) {
            addCriterion("Room_ID3 <=", value, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3Like(String value) {
            addCriterion("Room_ID3 like", value, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3NotLike(String value) {
            addCriterion("Room_ID3 not like", value, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3In(List<String> values) {
            addCriterion("Room_ID3 in", values, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3NotIn(List<String> values) {
            addCriterion("Room_ID3 not in", values, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3Between(String value1, String value2) {
            addCriterion("Room_ID3 between", value1, value2, "roomId3");
            return (Criteria) this;
        }

        public Criteria andRoomId3NotBetween(String value1, String value2) {
            addCriterion("Room_ID3 not between", value1, value2, "roomId3");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_to_room
     *
     * @mbg.generated do_not_delete_during_merge Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table order_to_room
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}