package com.uestc.fff.hotel.domain;

public class OrderTR {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_to_room.id
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_to_room.Order_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_to_room.Room_ID1
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String roomId1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_to_room.Room_ID2
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String roomId2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_to_room.Room_ID3
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    private String roomId3;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_to_room.id
     *
     * @return the value of order_to_room.id
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_to_room.id
     *
     * @param id the value for order_to_room.id
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_to_room.Order_ID
     *
     * @return the value of order_to_room.Order_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_to_room.Order_ID
     *
     * @param orderId the value for order_to_room.Order_ID
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_to_room.Room_ID1
     *
     * @return the value of order_to_room.Room_ID1
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getRoomId1() {
        return roomId1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_to_room.Room_ID1
     *
     * @param roomId1 the value for order_to_room.Room_ID1
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setRoomId1(String roomId1) {
        this.roomId1 = roomId1 == null ? null : roomId1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_to_room.Room_ID2
     *
     * @return the value of order_to_room.Room_ID2
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getRoomId2() {
        return roomId2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_to_room.Room_ID2
     *
     * @param roomId2 the value for order_to_room.Room_ID2
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setRoomId2(String roomId2) {
        this.roomId2 = roomId2 == null ? null : roomId2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_to_room.Room_ID3
     *
     * @return the value of order_to_room.Room_ID3
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public String getRoomId3() {
        return roomId3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_to_room.Room_ID3
     *
     * @param roomId3 the value for order_to_room.Room_ID3
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    public void setRoomId3(String roomId3) {
        this.roomId3 = roomId3 == null ? null : roomId3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        OrderTR other = (OrderTR) that;
        return (this.getId() == null ? other.getId() == null : this.getId().equals(other.getId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getRoomId1() == null ? other.getRoomId1() == null : this.getRoomId1().equals(other.getRoomId1()))
            && (this.getRoomId2() == null ? other.getRoomId2() == null : this.getRoomId2().equals(other.getRoomId2()))
            && (this.getRoomId3() == null ? other.getRoomId3() == null : this.getRoomId3().equals(other.getRoomId3()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_to_room
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getId() == null) ? 0 : getId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getRoomId1() == null) ? 0 : getRoomId1().hashCode());
        result = prime * result + ((getRoomId2() == null) ? 0 : getRoomId2().hashCode());
        result = prime * result + ((getRoomId3() == null) ? 0 : getRoomId3().hashCode());
        return result;
    }
}