package com.uestc.fff.hotel.domain;

public class RoomInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.RoomID
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    private String roomid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.Hotel_id
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    private String hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.Order_ID
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.Room_Last
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    private Integer roomLast;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.Room_Type
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    private String roomType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.Room_Status
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    private Boolean roomStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.Room_Fee
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    private Float roomFee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column room_info.Room_Breakfirst
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    private String roomBreakfirst;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.RoomID
     *
     * @return the value of room_info.RoomID
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public String getRoomid() {
        return roomid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.RoomID
     *
     * @param roomid the value for room_info.RoomID
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setRoomid(String roomid) {
        this.roomid = roomid == null ? null : roomid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.Hotel_id
     *
     * @return the value of room_info.Hotel_id
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public String getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.Hotel_id
     *
     * @param hotelId the value for room_info.Hotel_id
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setHotelId(String hotelId) {
        this.hotelId = hotelId == null ? null : hotelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.Order_ID
     *
     * @return the value of room_info.Order_ID
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.Order_ID
     *
     * @param orderId the value for room_info.Order_ID
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.Room_Last
     *
     * @return the value of room_info.Room_Last
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public Integer getRoomLast() {
        return roomLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.Room_Last
     *
     * @param roomLast the value for room_info.Room_Last
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setRoomLast(Integer roomLast) {
        this.roomLast = roomLast;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.Room_Type
     *
     * @return the value of room_info.Room_Type
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public String getRoomType() {
        return roomType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.Room_Type
     *
     * @param roomType the value for room_info.Room_Type
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setRoomType(String roomType) {
        this.roomType = roomType == null ? null : roomType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.Room_Status
     *
     * @return the value of room_info.Room_Status
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public Boolean getRoomStatus() {
        return roomStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.Room_Status
     *
     * @param roomStatus the value for room_info.Room_Status
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setRoomStatus(Boolean roomStatus) {
        this.roomStatus = roomStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.Room_Fee
     *
     * @return the value of room_info.Room_Fee
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public Float getRoomFee() {
        return roomFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.Room_Fee
     *
     * @param roomFee the value for room_info.Room_Fee
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setRoomFee(Float roomFee) {
        this.roomFee = roomFee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column room_info.Room_Breakfirst
     *
     * @return the value of room_info.Room_Breakfirst
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public String getRoomBreakfirst() {
        return roomBreakfirst;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column room_info.Room_Breakfirst
     *
     * @param roomBreakfirst the value for room_info.Room_Breakfirst
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    public void setRoomBreakfirst(String roomBreakfirst) {
        this.roomBreakfirst = roomBreakfirst == null ? null : roomBreakfirst.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        RoomInfo other = (RoomInfo) that;
        return (this.getRoomid() == null ? other.getRoomid() == null : this.getRoomid().equals(other.getRoomid()))
            && (this.getHotelId() == null ? other.getHotelId() == null : this.getHotelId().equals(other.getHotelId()))
            && (this.getOrderId() == null ? other.getOrderId() == null : this.getOrderId().equals(other.getOrderId()))
            && (this.getRoomLast() == null ? other.getRoomLast() == null : this.getRoomLast().equals(other.getRoomLast()))
            && (this.getRoomType() == null ? other.getRoomType() == null : this.getRoomType().equals(other.getRoomType()))
            && (this.getRoomStatus() == null ? other.getRoomStatus() == null : this.getRoomStatus().equals(other.getRoomStatus()))
            && (this.getRoomFee() == null ? other.getRoomFee() == null : this.getRoomFee().equals(other.getRoomFee()))
            && (this.getRoomBreakfirst() == null ? other.getRoomBreakfirst() == null : this.getRoomBreakfirst().equals(other.getRoomBreakfirst()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 16:03:08 GMT+08:00 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRoomid() == null) ? 0 : getRoomid().hashCode());
        result = prime * result + ((getHotelId() == null) ? 0 : getHotelId().hashCode());
        result = prime * result + ((getOrderId() == null) ? 0 : getOrderId().hashCode());
        result = prime * result + ((getRoomLast() == null) ? 0 : getRoomLast().hashCode());
        result = prime * result + ((getRoomType() == null) ? 0 : getRoomType().hashCode());
        result = prime * result + ((getRoomStatus() == null) ? 0 : getRoomStatus().hashCode());
        result = prime * result + ((getRoomFee() == null) ? 0 : getRoomFee().hashCode());
        result = prime * result + ((getRoomBreakfirst() == null) ? 0 : getRoomBreakfirst().hashCode());
        return result;
    }
}