package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.City;
import com.uestc.fff.hotel.domain.CityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    long countByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int deleteByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    City selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExample(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKey(City record);
}