package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.City;
import com.uestc.fff.hotel.domain.CityExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CityMapper extends CityMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    long countByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insert(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insertSelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    List<City> selectByExample(CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    City selectByPrimaryKey(String cityId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExampleSelective(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExample(@Param("record") City record, @Param("example") CityExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKeySelective(City record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table city
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKey(City record);
}