package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.Continent;
import com.uestc.fff.hotel.domain.ContinentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContinentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    long countByExample(ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    int deleteByExample(ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    int deleteByPrimaryKey(String contimentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    int insert(Continent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    int insertSelective(Continent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    List<Continent> selectByExample(ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    Continent selectByPrimaryKey(String contimentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    int updateByExampleSelective(@Param("record") Continent record, @Param("example") ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    int updateByExample(@Param("record") Continent record, @Param("example") ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    int updateByPrimaryKeySelective(Continent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
     * @mbg.generated Tue Jul 30 15:53:19 CST 2019
     */
    int updateByPrimaryKey(Continent record);
}