package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.Continent;
import com.uestc.fff.hotel.domain.ContinentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContinentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    long countByExample(ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByExample(ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByPrimaryKey(String contimentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insert(Continent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insertSelective(Continent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    List<Continent> selectByExample(ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    Continent selectByPrimaryKey(String contimentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExampleSelective(@Param("record") Continent record, @Param("example") ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExample(@Param("record") Continent record, @Param("example") ContinentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKeySelective(Continent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table continent
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKey(Continent record);
}