package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.Country;
import com.uestc.fff.hotel.domain.CountryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    long countByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    int deleteByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    int deleteByPrimaryKey(String countryCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    int insertSelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    List<Country> selectByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    Country selectByPrimaryKey(String countryCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    int updateByExample(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
     * @mbg.generated Sun Aug 04 09:25:55 GMT+08:00 2019
     */
    int updateByPrimaryKey(Country record);
}