package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.Country;
import com.uestc.fff.hotel.domain.CountryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountryMapper extends CountryMapperExt{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    long countByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByPrimaryKey(String countryCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insertSelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    List<Country> selectByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    Country selectByPrimaryKey(String countryCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExampleSelective(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExample(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKeySelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKey(Country record);
}