package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.Country;
import com.uestc.fff.hotel.domain.CountryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CountryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    long countByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int deleteByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int deleteByPrimaryKey(String countryCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int insert(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int insertSelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    List<Country> selectByExample(CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    Country selectByPrimaryKey(String countryCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExampleSelective(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExample(@Param("record") Country record, @Param("example") CountryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKeySelective(Country record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table country
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKey(Country record);
}