package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.HotelInfo;
import com.uestc.fff.hotel.domain.HotelInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    long countByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int deleteByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int deleteByPrimaryKey(String hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int insert(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int insertSelective(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    List<HotelInfo> selectByExampleWithBLOBs(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    List<HotelInfo> selectByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    HotelInfo selectByPrimaryKey(String hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExampleSelective(@Param("record") HotelInfo record, @Param("example") HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExampleWithBLOBs(@Param("record") HotelInfo record, @Param("example") HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExample(@Param("record") HotelInfo record, @Param("example") HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKeySelective(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKeyWithBLOBs(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
<<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
=======
     * @mbg.generated Tue Jul 30 16:48:09 CST 2019
>>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKey(HotelInfo record);
}