package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.HotelInfo;
import com.uestc.fff.hotel.domain.HotelInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HotelInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    long countByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int deleteByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int deleteByPrimaryKey(String hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int insert(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int insertSelective(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    List<HotelInfo> selectByExampleWithBLOBs(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    List<HotelInfo> selectByExample(HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    HotelInfo selectByPrimaryKey(String hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int updateByExampleSelective(@Param("record") HotelInfo record, @Param("example") HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") HotelInfo record, @Param("example") HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int updateByExample(@Param("record") HotelInfo record, @Param("example") HotelInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int updateByPrimaryKeySelective(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(HotelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hotel_info
     *
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
     */
    int updateByPrimaryKey(HotelInfo record);
}