package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.RoomInfo;
import com.uestc.fff.hotel.domain.RoomInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    long countByExample(RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    int deleteByExample(RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    int deleteByPrimaryKey(String roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    int insert(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    int insertSelective(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    List<RoomInfo> selectByExample(RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    RoomInfo selectByPrimaryKey(String roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    int updateByExampleSelective(@Param("record") RoomInfo record, @Param("example") RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    int updateByExample(@Param("record") RoomInfo record, @Param("example") RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    int updateByPrimaryKeySelective(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
     * @mbg.generated Fri Aug 02 10:25:39 CST 2019
     */
    int updateByPrimaryKey(RoomInfo record);
}