package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.RoomInfo;
import com.uestc.fff.hotel.domain.RoomInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface RoomInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    long countByExample(RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByExample(RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByPrimaryKey(String roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insert(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insertSelective(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    List<RoomInfo> selectByExample(RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    RoomInfo selectByPrimaryKey(String roomid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExampleSelective(@Param("record") RoomInfo record, @Param("example") RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExample(@Param("record") RoomInfo record, @Param("example") RoomInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKeySelective(RoomInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table room_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKey(RoomInfo record);
}