package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.UserInfo;
import com.uestc.fff.hotel.domain.UserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    UserInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
<<<<<<< HEAD
     * @mbg.generated Tue Jul 30 16:09:21 CST 2019
=======
     * @mbg.generated Thu Jul 25 14:23:43 CST 2019
>>>>>>> 2b0298d56bc9aac760a69e2d6eae44e806f4fc9b
     */
    int updateByPrimaryKey(UserInfo record);
}