package com.uestc.fff.hotel.mapper;

import com.uestc.fff.hotel.domain.UserInfo;
import com.uestc.fff.hotel.domain.UserInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    long countByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int deleteByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int deleteByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int insert(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int insertSelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    List<UserInfo> selectByExample(UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    UserInfo selectByPrimaryKey(String userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExampleSelective(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByExample(@Param("record") UserInfo record, @Param("example") UserInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKeySelective(UserInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     <<<<<<< HEAD
     * @mbg.generated Mon Jul 29 10:01:50 GMT+08:00 2019
    =======
     * @mbg.generated Tue Jul 30 16:48:10 CST 2019
    >>>>>>> 608a0e28e1613718fa4ca2e091c3d7c2f6631cc0
     */
    int updateByPrimaryKey(UserInfo record);
}